### ISSUE TITLE
Feedのリンク先が404になってしまう

### ISSUE THREAD

**Issue by igrep** [lotz84/lotz84.github.io#5]
お気づきかもしれませんが、 https://github.com/lotz84/lotz84.github.io/blob/b3d2440f662c3d7a129227dfe787f3e97f66d269/feed.xml#L13 のように、
feed.xmlに書かれているリンク先が `http://lotz84.github.io/posts//posts/a-story-of-typing-web-api.html` と、 余計な `/posts/` がついているために404になってしまうようです。

結果 https://haskell.jp/antenna/ で lotz84.github.io の記事をクリックすると404になってしまいます。

**Comment by lotz84** [comment]
ありがとうございます。 https://github.com/lotz84/lotz84.github.io/commit/33fce96fe364ed7914961330cfa0fc40f18eedb2 にて修正しました
